### ISSUE TITLE
Let sidebar's theme list to be browser with arrow keys

### ISSUE THREAD

**Issue by Frondor** [rainglow/preview#1]
It would be handy if we can browse the theme's list at https://rainglow.io/preview/ with `up` and `down` arrow keys :+1:

**Comment by daylerees** [comment]
This is something I'd definitely like to add when I find 5 minutes. Will keep you informed mate. :)

**Comment by daylerees** [comment]
Your wish be done! https://rainglow.io/preview/#peacock :)
